# Generated by Django 5.1.2 on 2024-12-08 06:30

import django.db.models.deletion
import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact_Info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('contact_info', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Master',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service', models.CharField(max_length=32)),
                ('master_name', models.CharField(max_length=16)),
                ('master_name_en', models.CharField(max_length=16, null=True)),
                ('master_name_ru', models.CharField(max_length=16, null=True)),
                ('master_name_ky', models.CharField(max_length=16, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='master_image')),
                ('description', models.TextField()),
                ('description_en', models.TextField(null=True)),
                ('description_ru', models.TextField(null=True)),
                ('description_ky', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='СompanyProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=16)),
                ('company_name_en', models.CharField(max_length=16, null=True)),
                ('company_name_ru', models.CharField(max_length=16, null=True)),
                ('company_name_ky', models.CharField(max_length=16, null=True)),
                ('description', models.TextField()),
                ('description_en', models.TextField(null=True)),
                ('description_ru', models.TextField(null=True)),
                ('description_ky', models.TextField(null=True)),
                ('experience', models.SmallIntegerField()),
                ('masters', models.SmallIntegerField()),
                ('clients', models.SmallIntegerField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='company_image/')),
            ],
        ),
        migrations.CreateModel(
            name='Services',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('services_name', models.CharField(max_length=16)),
                ('services_name_en', models.CharField(max_length=16, null=True)),
                ('services_name_ru', models.CharField(max_length=16, null=True)),
                ('services_name_ky', models.CharField(max_length=16, null=True)),
                ('price', models.PositiveSmallIntegerField()),
                ('description', models.TextField()),
                ('description_en', models.TextField(null=True)),
                ('description_ru', models.TextField(null=True)),
                ('description_ky', models.TextField(null=True)),
                ('master', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='shop.master')),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author_name', models.CharField(max_length=52, unique=True)),
                ('comment', models.TextField()),
                ('crated_date', models.DateTimeField(auto_now_add=True)),
                ('master', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='master_name_master', to='shop.master')),
                ('servise', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='service_name_service', to='shop.services')),
            ],
        ),
    ]
