# Generated by Django 5.1.2 on 2024-12-08 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_master_company'),
    ]

    operations = [
        migrations.CreateModel(
            name='Servise_type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_type', models.CharField(max_length=65)),
                ('price', models.PositiveSmallIntegerField()),
            ],
        ),
        migrations.RemoveField(
            model_name='services',
            name='price',
        ),
    ]
