# Generated by Django 5.1.2 on 2024-11-29 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_remove_contactinfo_master_contactinfo_companyprofile_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='services',
            name='description_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='services',
            name='description_ky',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='services',
            name='description_ru',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='services',
            name='services_name_en',
            field=models.CharField(max_length=16, null=True),
        ),
        migrations.AddField(
            model_name='services',
            name='services_name_ky',
            field=models.CharField(max_length=16, null=True),
        ),
        migrations.AddField(
            model_name='services',
            name='services_name_ru',
            field=models.CharField(max_length=16, null=True),
        ),
        migrations.AddField(
            model_name='сompanyprofile',
            name='company_name_en',
            field=models.CharField(max_length=16, null=True),
        ),
        migrations.AddField(
            model_name='сompanyprofile',
            name='company_name_ky',
            field=models.CharField(max_length=16, null=True),
        ),
        migrations.AddField(
            model_name='сompanyprofile',
            name='company_name_ru',
            field=models.CharField(max_length=16, null=True),
        ),
        migrations.AddField(
            model_name='сompanyprofile',
            name='description_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='сompanyprofile',
            name='description_ky',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='сompanyprofile',
            name='description_ru',
            field=models.TextField(null=True),
        ),
    ]
