# Generated by Django 5.1.2 on 2024-12-08 07:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_servise_type_remove_services_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='servise_type',
            name='sirvice',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='shop.services'),
            preserve_default=False,
        ),
    ]
