# Generated by Django 5.1.2 on 2024-12-08 07:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_servise_type_sirvice'),
    ]

    operations = [
        migrations.RenameField(
            model_name='servise_type',
            old_name='sirvice',
            new_name='service',
        ),
    ]
