# Generated by Django 5.1.2 on 2024-11-29 06:29

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_services_description_en_services_description_ky_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='age',
            field=models.SmallIntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(80), django.core.validators.MinValueValidator(18)]),
        ),
        migrations.DeleteModel(
            name='СatalogProfileImage',
        ),
    ]
