# Generated by Django 5.1.2 on 2024-11-29 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_alter_user_age_delete_сatalogprofileimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='master',
            name='description_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='master',
            name='description_ky',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='master',
            name='description_ru',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='master',
            name='master_name_en',
            field=models.CharField(max_length=16, null=True),
        ),
        migrations.AddField(
            model_name='master',
            name='master_name_ky',
            field=models.CharField(max_length=16, null=True),
        ),
        migrations.AddField(
            model_name='master',
            name='master_name_ru',
            field=models.CharField(max_length=16, null=True),
        ),
    ]
