# Generated by Django 5.1.2 on 2024-11-29 10:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0009_remove_сompanyprofile_company_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gallery',
            name='gallery_image',
        ),
        migrations.RemoveField(
            model_name='gallery',
            name='image',
        ),
        migrations.RemoveField(
            model_name='glavnyiimage',
            name='description',
        ),
        migrations.RemoveField(
            model_name='glavnyiimage',
            name='description_en',
        ),
        migrations.RemoveField(
            model_name='glavnyiimage',
            name='description_ky',
        ),
        migrations.RemoveField(
            model_name='glavnyiimage',
            name='description_ru',
        ),
        migrations.RemoveField(
            model_name='glavnyiimage',
            name='work_name',
        ),
        migrations.RemoveField(
            model_name='glavnyiimage',
            name='work_name_en',
        ),
        migrations.RemoveField(
            model_name='glavnyiimage',
            name='work_name_ky',
        ),
        migrations.RemoveField(
            model_name='glavnyiimage',
            name='work_name_ru',
        ),
        migrations.AddField(
            model_name='gallery',
            name='description',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='gallery',
            name='description_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='gallery',
            name='description_ky',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='gallery',
            name='description_ru',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='gallery',
            name='work_name',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='gallery',
            name='work_name_en',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='gallery',
            name='work_name_ky',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='gallery',
            name='work_name_ru',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='glavnyiimage',
            name='gallery',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='shop.gallery'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='glavnyiimage',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='image'),
        ),
    ]
