# Generated by Django 5.1.2 on 2024-11-29 10:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0010_remove_gallery_gallery_image_remove_gallery_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='glavnyiimage',
            name='gallery',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery', to='shop.gallery'),
        ),
    ]
