# Generated by Django 5.1.2 on 2024-11-29 10:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0011_alter_glavnyiimage_gallery'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartitem',
            name='servise',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cart_servise', to='shop.services'),
        ),
    ]
