# Generated by Django 5.1.2 on 2024-12-01 04:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0012_alter_cartitem_servise'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='user',
        ),
        migrations.RemoveField(
            model_name='cartitem',
            name='cart',
        ),
        migrations.RemoveField(
            model_name='cartitem',
            name='servise',
        ),
        migrations.DeleteModel(
            name='Catalog',
        ),
        migrations.RemoveField(
            model_name='contactinfo',
            name='companyProfile',
        ),
        migrations.AddField(
            model_name='contact_info',
            name='companyProfile',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='shop.сompanyprofile'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Cart',
        ),
        migrations.DeleteModel(
            name='CartItem',
        ),
        migrations.DeleteModel(
            name='ContactInfo',
        ),
    ]
