# Generated by Django 5.1.2 on 2024-12-01 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0013_remove_cart_user_remove_cartitem_cart_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='client',
        ),
        migrations.AddField(
            model_name='review',
            name='author_name',
            field=models.CharField(default=1, max_length=52, unique=True),
            preserve_default=False,
        ),
    ]
